DROP TABLE IF EXISTS urls;
DROP TABLE IF EXISTS url_checks;

CREATE TABLE urls (
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(255) UNIQUE NOT NULL,
	created_at TIMESTAMP NOT NULL
);

CREATE TABLE url_checks (
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	url_id BIGINT REFERENCES urls (id) ON DELETE CASCADE NOT NULL,
	status_code INT,
	h1 TEXT,
	title TEXT,
	description TEXT,
	created_at TIMESTAMP NOT NULL
);
